spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/watch-api
    username: postgres
    password: s3cr3t
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
